"""restructuring

Revision ID: 14a28dcfc3e9
Revises: 5a97e73f4a16
Create Date: 2024-03-09 21:07:37.626607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a28dcfc3e9'
down_revision = '5a97e73f4a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_constraint('business_file_id_fkey', type_='foreignkey')
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('business_file_id_fkey', 'file', ['file_id'], ['id'])

    # ### end Alembic commands ###
