"""added new column to code tb

Revision ID: 1b61f679f165
Revises: 30de82b1a0dc
Create Date: 2024-01-21 03:18:50.025966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b61f679f165'
down_revision = '30de82b1a0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('account')

    # ### end Alembic commands ###
