"""initial migration 004

Revision ID: 51efd7626099
Revises: 5ffa4ed16b8c
Create Date: 2024-01-14 12:04:08.981529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51efd7626099'
down_revision = '5ffa4ed16b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('digital_address_4', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('digital_address_4')

    # ### end Alembic commands ###
