"""relation Transaction table with apiket table

Revision ID: 545e0f6b473a
Revises: cc09677c16fe
Create Date: 2024-03-26 00:16:35.711147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545e0f6b473a'
down_revision = 'cc09677c16fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apikey_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'apikey', ['apikey_id'], ['apikey_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('apikey_id')

    # ### end Alembic commands ###
