"""initial migration 004

Revision ID: 5ffa4ed16b8c
Revises: eb2c30ba8889
Create Date: 2024-01-14 11:57:14.155984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffa4ed16b8c'
down_revision = 'eb2c30ba8889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('business_name')

    # ### end Alembic commands ###
