"""migration 01

Revision ID: 88ab67948ece
Revises: 51efd7626099
Create Date: 2024-01-14 12:05:55.633141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ab67948ece'
down_revision = '51efd7626099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('digital_address_4')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('digital_address_4', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
