"""file table issues

Revision ID: 9c1757c0f240
Revises: 14a28dcfc3e9
Create Date: 2024-03-09 23:16:43.581853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1757c0f240'
down_revision = '14a28dcfc3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'file', ['file_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
