"""migration transaction

Revision ID: a2a3e07b01d4
Revises: 3bb445ab408f
Create Date: 2024-03-21 23:45:04.709847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a3e07b01d4'
down_revision = '3bb445ab408f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('status_message')
        batch_op.drop_column('status_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status_message', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
