"""relation Transaction table with apiket table

Revision ID: cc09677c16fe
Revises: cfed4504121f
Create Date: 2024-03-26 00:12:02.782776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc09677c16fe'
down_revision = 'cfed4504121f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('apikey_reference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apikey_reference', sa.VARCHAR(length=422), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
