"""relation Transaction table with apiket table

Revision ID: cfed4504121f
Revises: fad284f8114e
Create Date: 2024-03-26 00:01:28.734003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfed4504121f'
down_revision = 'fad284f8114e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.drop_constraint('apikey_transaction_id_fkey', type_='foreignkey')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('apikey_transaction_id_fkey', 'transaction', ['transaction_id'], ['transaction_id'])

    # ### end Alembic commands ###
