"""initial migration

Revision ID: d497a9a33337
Revises: 
Create Date: 2023-12-27 23:40:48.601762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd497a9a33337'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['apikey_id'])

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['business_id'])

    with op.batch_alter_table('kyc', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['kyc_id'])

    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['settlement_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('kyc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
