"""initial migration 004

Revision ID: eb2c30ba8889
Revises: 81f228f96f4a
Create Date: 2024-01-14 11:55:34.459651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2c30ba8889'
down_revision = '81f228f96f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('business_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
