"""migration 001

Revision ID: f0a16a547f2b
Revises: 
Create Date: 2024-04-13 23:47:10.498937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a16a547f2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('apikey_id', sa.String(length=36), nullable=False),
    sa.Column('apikey_name', sa.String(length=80), nullable=True),
    sa.Column('apikey_description', sa.String(length=80), nullable=True),
    sa.Column('apikey_status', sa.String(length=12), nullable=True),
    sa.Column('apikey', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('apikey_id'),
    sa.UniqueConstraint('apikey_id')
    )
    op.create_table('code',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('account', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('kyc',
    sa.Column('kyc_id', sa.String(length=36), nullable=False),
    sa.Column('registration_documents', sa.String(length=120), nullable=True),
    sa.Column('director_1_document', sa.String(length=120), nullable=True),
    sa.Column('director_2_document', sa.String(length=120), nullable=True),
    sa.Column('other_documents', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('kyc_id'),
    sa.UniqueConstraint('kyc_id')
    )
    op.create_table('settlement',
    sa.Column('settlement_id', sa.String(length=36), nullable=False),
    sa.Column('account_holder_name', sa.String(length=80), nullable=True),
    sa.Column('account_number', sa.String(length=80), nullable=True),
    sa.Column('bank_name', sa.String(length=80), nullable=True),
    sa.Column('bank_branch_name', sa.String(length=80), nullable=True),
    sa.Column('bank_swift_code', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('settlement_id'),
    sa.UniqueConstraint('settlement_id')
    )
    op.create_table('business',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('digital_address', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('business_account_status', sa.String(length=12), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('kyc_id', sa.String(length=36), nullable=True),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('settlement_id', sa.String(length=36), nullable=True),
    sa.Column('apikey_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['apikey_id'], ['apikey.apikey_id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc.kyc_id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement.settlement_id'], ),
    sa.PrimaryKeyConstraint('business_id'),
    sa.UniqueConstraint('business_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_reference', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.String(length=12), nullable=True),
    sa.Column('currency', sa.String(length=12), nullable=True),
    sa.Column('fee', sa.String(length=12), nullable=True),
    sa.Column('tax', sa.String(length=12), nullable=True),
    sa.Column('source_metadata', sa.String(length=422), nullable=True),
    sa.Column('destination_metadata', sa.String(length=422), nullable=True),
    sa.Column('external_service_provider', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('apikey_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['apikey_id'], ['apikey.apikey_id'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'transaction_reference'),
    sa.UniqueConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('other_name', sa.String(length=80), nullable=True),
    sa.Column('logo', sa.String(length=120), nullable=True),
    sa.Column('account_type', sa.String(length=22), nullable=True),
    sa.Column('active_status', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('business_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.business_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transaction')
    op.drop_table('business')
    op.drop_table('settlement')
    op.drop_table('kyc')
    op.drop_table('file')
    op.drop_table('code')
    op.drop_table('apikey')
    # ### end Alembic commands ###
